// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfU68gHjBwMfEc10t2hvDTkVKi1tUA4i0',
    appId: '1:47535989137:web:5e0826b09506ab3f04fa30',
    messagingSenderId: '47535989137',
    projectId: 'componentes5c',
    authDomain: 'componentes5c.firebaseapp.com',
    storageBucket: 'componentes5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEcP51jQ49JvDmRMa7MvIY0tYLPi5Tvw',
    appId: '1:47535989137:android:db90f24b9ed1639004fa30',
    messagingSenderId: '47535989137',
    projectId: 'componentes5c',
    storageBucket: 'componentes5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtmEjWC02k8G39QfRwjZzse6SBwF0Q7c',
    appId: '1:47535989137:ios:cd546d557f4c550f04fa30',
    messagingSenderId: '47535989137',
    projectId: 'componentes5c',
    storageBucket: 'componentes5c.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
